const data = {
    products: [
        {
            _id: '1',
            name: 'Nike slim shirt',
            category: 'shirts',
            image: '/images/virat.jpg',
            price: 240,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        }, 
        {
            _id: '2',
            name: 'Adidas slim shirt',
            category: 'shirts',
            image: '/images/dybala.jpg',
            price: 240,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Raymond slim shirt',
            category: 'shirts',
            image: '/images/neymar.jpg',
            price: 240,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike slim shirt',
            category: 'shirts',
            image: '/images/dybala.jpg',
            price: 240,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike slim shirt',
            category: 'shirts',
            image: '/images/ronaldo.jpg',
            price: 240,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike slim shirt',
            category: 'shirts',
            image: '/images/virat.jpg',
            price: 240,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
    ],
};
export default data;